"""Remove lecturer from Course

Revision ID: 3f66ccca19f7
Revises: 
Create Date: 2025-06-24 08:49:22.656003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f66ccca19f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('lecturer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
